services:
  db:
    image: postgres:17-alpine
    container_name: ocr-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ocr-app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ocr-app-network

volumes:
  db_data:

networks:
  ocr-app-network:
    driver: bridge
